name: Link Checker
# using https://github.com/lycheeverse/lychee-action

on:
  workflow_dispatch
  # push
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.1.1
        with:
          args: --verbose --no-progress **/*.md **/*.htm **/*.html
