name: Link Checker
# using https://github.com/lycheeverse/lychee-action

on:
  workflow_dispatch
  # push

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.4
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

        with:
          args: --verbose --no-progress ./**/*.md ./**/*.htm ./**/*.html

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
